import type { Post, Event, Conversation, Message, Notification, Story } from '../types';

// ─── SPORT CONSTANTS ────────────────────────────────────────────────────────
// Re-exported from lib/constants for backward compatibility.
// Import directly from '@/lib/constants' in new code.
export { SPORT_CATEGORIES, GLOBAL_SPORTS, SPORT_POSITIONS } from '@/lib/constants';

// ─── MOCK USERS REMOVED ─────────────────────────────────────────────────────
// MOCK_USERS has been removed. Profile data now comes from Appwrite.
// Use profileService.ts (searchProfiles, getProfile, etc.) instead.

// ─── PLACEHOLDER AVATARS (used by still-mock collections below) ──────────────
const PLACEHOLDER_AVATARS: Record<string, string> = {
  u1: 'https://i.pravatar.cc/150?img=11',
  u2: 'https://i.pravatar.cc/150?img=47',
  u3: 'https://i.pravatar.cc/150?img=12',
  u4: 'https://i.pravatar.cc/150?img=5',
  u5: 'https://i.pravatar.cc/150?img=33',
  u6: 'https://i.pravatar.cc/150?img=62',
  u7: 'https://i.pravatar.cc/150?img=13',
  u8: 'https://i.pravatar.cc/150?img=9',
  u9: 'https://i.pravatar.cc/150?img=59',
  u10: 'https://i.pravatar.cc/150?img=15',
  cu1: 'https://i.pravatar.cc/150?img=11',
};
function ph(id: string) { return PLACEHOLDER_AVATARS[id] ?? `https://i.pravatar.cc/150?u=${id}`; }

// Legacy: kept only so MOCK_POSTS / MOCK_STORIES / MOCK_CONVERSATIONS /
// MOCK_NOTIFICATIONS can still reference a User-like shape.
// These will be migrated in a future phase.
const _MOCK_USER_STUBS = [
  { id: 'u1', uid: 'u1', name: 'Marcus Thielemann', username: 'marcus_thiel',
    email: 'marcus@sportix.io', avatar: ph('u1'),
    coverImage: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=1200&q=80',
    role: 'athlete', sport: 'football', sports: ['football'], location: 'Berlin, Germany',
    bio: '', experienceLevel: 'professional', openToRecruit: false, isOnline: true, isVerified: true,
    createdAt: '2023-06-01',
    stats: { matches: 284, events: 47, followers: 128400, following: 312, wins: 189, losses: 61, rating: 91, yearsExperience: 11 },
    performanceData: { speed: 88, strength: 79, endurance: 92, agility: 86, technique: 94, teamwork: 90 },
    achievements: [] as any[],
  },
  { id: 'u2', uid: 'u2', name: 'Priya Krishnamurthy', username: 'priya_k',
    email: 'priya@sportix.io', avatar: ph('u2'),
    coverImage: 'https://images.unsplash.com/photo-1547941126-3d5322b218b0?w=1200&q=80',
    role: 'athlete', sport: 'tennis', sports: ['tennis', 'badminton'], location: 'Mumbai, India',
    bio: '', experienceLevel: 'elite', openToRecruit: true, isOnline: false, isVerified: true,
    createdAt: '2023-02-14',
    stats: { matches: 412, events: 89, followers: 342000, following: 145, wins: 318, losses: 94, rating: 94, yearsExperience: 16 },
    performanceData: { speed: 92, strength: 74, endurance: 90, agility: 96, technique: 97, teamwork: 70 },
    achievements: [] as any[],
  },
  { id: 'u3', uid: 'u3', name: 'DeShawn Williams', username: 'deshawn_w',
    email: 'deshawn@sportix.io', avatar: ph('u3'),
    role: 'athlete', sport: 'basketball', sports: ['basketball'], location: 'Chicago, USA',
    bio: '', experienceLevel: 'professional', openToRecruit: false, isOnline: true, isVerified: true,
    createdAt: '2022-11-10',
    stats: { matches: 380, events: 72, followers: 215000, following: 280, wins: 241, losses: 139, rating: 88, yearsExperience: 12 },
    performanceData: { speed: 90, strength: 85, endurance: 88, agility: 93, technique: 87, teamwork: 84 },
    achievements: [] as any[],
  },
  { id: 'u4', uid: 'u4', name: 'Isabela Moraes', username: 'isabela_m',
    email: 'isabela@sportix.io', avatar: ph('u4'),
    role: 'athlete', sport: 'swimming', sports: ['swimming'], location: 'São Paulo, Brazil',
    bio: '', experienceLevel: 'elite', openToRecruit: false, isOnline: true, isVerified: true,
    createdAt: '2021-08-20',
    stats: { matches: 520, events: 105, followers: 485000, following: 201, wins: 408, losses: 112, rating: 96, yearsExperience: 18 },
    performanceData: { speed: 95, strength: 80, endurance: 98, agility: 88, technique: 96, teamwork: 75 },
    achievements: [] as any[],
  },
  { id: 'u5', uid: 'u5', name: 'Yuki Tanaka', username: 'yuki_t',
    email: 'yuki@sportix.io', avatar: ph('u5'),
    role: 'athlete', sport: 'mma', sports: ['mma', 'boxing'], location: 'Tokyo, Japan',
    bio: '', experienceLevel: 'professional', openToRecruit: false, isOnline: true, isVerified: true,
    createdAt: '2023-03-15',
    stats: { matches: 47, events: 18, followers: 89000, following: 124, wins: 43, losses: 4, rating: 93, yearsExperience: 8 },
    performanceData: { speed: 93, strength: 91, endurance: 89, agility: 95, technique: 97, teamwork: 72 },
    achievements: [] as any[],
  },
  { id: 'u6', uid: 'u6', name: 'Arjun Selvam', username: 'arjun_s',
    email: 'arjun@sportix.in', avatar: ph('u6'),
    role: 'athlete', sport: 'football', sports: ['football'], location: 'Chennai, Tamil Nadu, India',
    bio: '', experienceLevel: 'semi-pro', openToRecruit: true, isOnline: true, isVerified: false,
    createdAt: '2024-01-10',
    stats: { matches: 62, events: 15, followers: 8400, following: 210, wins: 39, losses: 23, rating: 82, yearsExperience: 4 },
    performanceData: { speed: 84, strength: 77, endurance: 80, agility: 86, technique: 81, teamwork: 88 },
    achievements: [] as any[],
  },
  { id: 'u7', uid: 'u7', name: 'Kavya Nair', username: 'kavya_n',
    email: 'kavya@sportix.in', avatar: ph('u7'),
    role: 'athlete', sport: 'cricket', sports: ['cricket', 'badminton'], location: 'Coimbatore, Tamil Nadu, India',
    bio: '', experienceLevel: 'amateur', openToRecruit: true, isOnline: false, isVerified: false,
    createdAt: '2024-02-20',
    stats: { matches: 34, events: 8, followers: 2100, following: 180, wins: 21, losses: 13, rating: 78, yearsExperience: 2 },
    performanceData: { speed: 78, strength: 68, endurance: 74, agility: 80, technique: 76, teamwork: 85 },
    achievements: [] as any[],
  },
  { id: 'u8', uid: 'u8', name: 'Pradeep Kumar', username: 'pradeep_k',
    email: 'pradeep@sportix.in', avatar: ph('u8'),
    role: 'athlete', sport: 'athletics', sports: ['athletics', 'cycling'], location: 'Madurai, Tamil Nadu, India',
    bio: '', experienceLevel: 'professional', openToRecruit: false, isOnline: true, isVerified: true,
    createdAt: '2023-08-05',
    stats: { matches: 148, events: 32, followers: 34000, following: 195, wins: 112, losses: 36, rating: 87, yearsExperience: 7 },
    performanceData: { speed: 94, strength: 76, endurance: 92, agility: 88, technique: 83, teamwork: 77 },
    achievements: [] as any[],
  },
  { id: 'u9', uid: 'u9', name: 'Riya Menon', username: 'riya_m',
    email: 'riya@sportix.in', avatar: ph('u9'),
    role: 'athlete', sport: 'basketball', sports: ['basketball'], location: 'Coimbatore, Tamil Nadu, India',
    bio: '', experienceLevel: 'semi-pro', openToRecruit: true, isOnline: false, isVerified: false,
    createdAt: '2023-11-15',
    stats: { matches: 110, events: 24, followers: 18000, following: 350, wins: 75, losses: 32, rating: 86, yearsExperience: 6 },
    performanceData: { speed: 86, strength: 78, endurance: 82, agility: 90, technique: 85, teamwork: 88 },
    achievements: [] as any[],
  },
  { id: 'u10', uid: 'u10', name: 'Sanjay Selvam', username: 'sanjay_s',
    email: 'sanjay@sportix.in', avatar: ph('u10'),
    role: 'athlete', sport: 'tennis', sports: ['tennis'], location: 'Trichy, Tamil Nadu, India',
    bio: '', experienceLevel: 'amateur', openToRecruit: true, isOnline: false, isVerified: false,
    createdAt: '2024-03-01',
    stats: { matches: 28, events: 5, followers: 1200, following: 95, wins: 15, losses: 13, rating: 74, yearsExperience: 2 },
    performanceData: { speed: 80, strength: 70, endurance: 76, agility: 82, technique: 72, teamwork: 65 },
    achievements: [] as any[],
  },
] as any[];

/** @deprecated Use profileService.searchProfiles() for real data */
export const MOCK_USERS = _MOCK_USER_STUBS;

// CURRENT_USER is intentionally removed. Use useAuthStore().user or
// useAuth().user for the authenticated user's data.


// ─── MOCK POSTS ────────────────────────────────────────────────────────────
export const MOCK_POSTS: Post[] = [
  {
    id: 'p1', authorId: 'u1', author: MOCK_USERS[0],
    content: 'Just wrapped up 3-hour tactical session with the analytics team. Heat maps don\'t lie — we\'re covering 37% more pressing zones this season. The data never sleeps. 📊⚽',
    mediaUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80',
    mediaType: 'image', category: 'training', timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
    reactions: { likes: ['cu1', 'u2', 'u3', 'u4', 'u5'], comments: [], shares: 28, saves: ['cu1', 'u4'] },
  },
  {
    id: 'p2', authorId: 'u2', author: MOCK_USERS[1],
    content: 'Roland Garros prep day 47. Serve speed up to 198 km/h. Return accuracy at 84%. Numbers are climbing — form is peaking at the right time. Clay season is mine. 🎾🔥',
    category: 'training', timestamp: new Date(Date.now() - 4 * 3600000).toISOString(),
    reactions: { likes: ['u1', 'u3', 'cu1'], comments: [], shares: 14, saves: [] },
  },
  {
    id: 'p3', authorId: 'u3', author: MOCK_USERS[2],
    content: '28 points. 11 assists. 9 rebounds. One bucket away from a triple-double. We move. Next game in 48 hours. No days off. 🏀💯',
    mediaUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&q=80',
    mediaType: 'image', category: 'highlights', timestamp: new Date(Date.now() - 6 * 3600000).toISOString(),
    reactions: { likes: ['cu1', 'u1', 'u2', 'u4'], comments: [], shares: 52, saves: ['cu1'] },
  },
  {
    id: 'p4', authorId: 'u4', author: MOCK_USERS[3],
    content: 'Olympic gold one year later. Still processing. Still working. The pool at 5AM never lies to you — it just shows you who you are. Back in training for World Champs. 🏊‍♀️🥇',
    mediaUrl: 'https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=800&q=80',
    mediaType: 'image', category: 'achievements', timestamp: new Date(Date.now() - 8 * 3600000).toISOString(),
    reactions: { likes: ['u1', 'u2', 'u3', 'u5', 'cu1'], comments: [], shares: 187, saves: ['cu1', 'u5'] },
  },
  {
    id: 'p5', authorId: 'u5', author: MOCK_USERS[4],
    content: 'Camp starts Monday. 8 weeks of hell before the title shot. My coaches say I\'m in the best shape of my life. My opponents should be scared. 12-0 and counting. 🥋💀',
    category: 'training', timestamp: new Date(Date.now() - 12 * 3600000).toISOString(),
    reactions: { likes: ['cu1', 'u1', 'u3'], comments: [], shares: 31, saves: [] },
  },
  {
    id: 'p6', authorId: 'u7', author: MOCK_USERS[6],
    content: 'Just smashed a century (104* off 55 balls) at the Trichy Cricket Super Bash! AI rating gave me a 9.4 SSR today. Absolute peak vibes no cap. 🏏🔥⚡ #cricket #flex',
    mediaUrl: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&q=80',
    mediaType: 'image', category: 'highlights', timestamp: new Date(Date.now() - 1 * 3600000).toISOString(),
    reactions: { likes: ['cu1', 'u6', 'u8', 'u9'], comments: [], shares: 42, saves: ['cu1'] },
  },
  {
    id: 'p7', authorId: 'u6', author: MOCK_USERS[5],
    content: 'Scored 4 goals in today\'s Chennai Futsal Derby! We took the victory 5-2. AI AutoSquad set up a clean 91% chemistry lineup that worked perfectly fr fr. ⚽🏆 #futsal #letuscook',
    mediaUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&q=80',
    mediaType: 'image', category: 'highlights', timestamp: new Date(Date.now() - 5 * 3600000).toISOString(),
    reactions: { likes: ['cu1', 'u7', 'u10'], comments: [], shares: 19, saves: [] },
  },
  {
    id: 'p8', authorId: 'u8', author: MOCK_USERS[7],
    content: 'Coimbatore 10K running challenge done! Smashed my previous PR by 2 minutes. Average pace: 4:12/km. Strength and endurance metrics are green. We are locked in! 🏃‍♀️🥇 #running #kovai',
    mediaUrl: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800&q=80',
    mediaType: 'image', category: 'achievements', timestamp: new Date(Date.now() - 10 * 3600000).toISOString(),
    reactions: { likes: ['u6', 'u7', 'cu1'], comments: [], shares: 15, saves: ['cu1'] },
  },
  {
    id: 'p9', authorId: 'u9', author: MOCK_USERS[8],
    content: 'Flexing our 91% AI chemistry match from the Coimbatore Hoopfest 3x3! The defense was on lock. We going all the way this season, no cap 🏀🔒 #basketball #fiba3x3',
    mediaUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&q=80',
    mediaType: 'image', category: 'highlights', timestamp: new Date(Date.now() - 14 * 3600000).toISOString(),
    reactions: { likes: ['cu1', 'u8', 'u10'], comments: [], shares: 8, saves: [] },
  },
  {
    id: 'p10', authorId: 'u6', author: MOCK_USERS[5],
    content: 'Just registered for the Tirunelveli Kabaddi Championship! Looking to crush it. The stamina metrics are up. Let\'s go guys! 🏆🔥 #kabaddi #tamilnadu #flex',
    mediaUrl: 'https://images.unsplash.com/photo-1519766304817-4f37bda74a27?w=800&q=80',
    mediaType: 'image', category: 'training', timestamp: new Date(Date.now() - 3 * 3600000).toISOString(),
    reactions: { likes: ['cu1', 'u7', 'u8'], comments: [], shares: 12, saves: [] },
  },
  {
    id: 'p11', authorId: 'u8', author: MOCK_USERS[7],
    content: 'Sunset Coastal Run in Kanyakumari is next! 🌅 Smashed a 5K training block in 18:42 today. Pure green metrics. We flexin\' the grind. #running #kanyakumari #flex',
    mediaUrl: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800&q=80',
    mediaType: 'image', category: 'training', timestamp: new Date(Date.now() - 8 * 3600000).toISOString(),
    reactions: { likes: ['cu1', 'u6', 'u10'], comments: [], shares: 25, saves: ['cu1'] },
  },
  {
    id: 'p12', authorId: 'u10', author: MOCK_USERS[9],
    content: 'Futsal scrimmage at Vellore View Turf done! Smashed it 6-3. AI AutoSquad recommendation was 10/10. Real teamwork. #futsal #vellore #squad',
    mediaUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&q=80',
    mediaType: 'image', category: 'highlights', timestamp: new Date(Date.now() - 11 * 3600000).toISOString(),
    reactions: { likes: ['cu1', 'u6', 'u7'], comments: [], shares: 9, saves: [] },
  },
  {
    id: 'p13', authorId: 'u7', author: MOCK_USERS[6],
    content: 'Ready for Thanjavur Palace Badminton Open! 🏸 Racquets re-strung at 28 lbs. The backhand smash is on lock. #badminton #thanjavur #clashhub',
    mediaUrl: 'https://images.unsplash.com/photo-1560079007-f530de68e8bb?w=800&q=80',
    mediaType: 'image', category: 'training', timestamp: new Date(Date.now() - 16 * 3600000).toISOString(),
    reactions: { likes: ['u6', 'u2', 'cu1'], comments: [], shares: 14, saves: [] },
  },
  {
    id: 'p14', authorId: 'u9', author: MOCK_USERS[8],
    content: 'MMA fight camp in Salem is absolute heat! 🥋 Cage work, wrestling drills, and sparring. Ready to flex our skills. 💀 #mma #salem #fightcamp',
    mediaUrl: 'https://images.unsplash.com/photo-1595078475328-1ab05d0a6a0e?w=800&q=80',
    mediaType: 'image', category: 'highlights', timestamp: new Date(Date.now() - 20 * 3600000).toISOString(),
    reactions: { likes: ['cu1', 'u7', 'u8', 'u10'], comments: [], shares: 38, saves: ['cu1'] },
  },
];

// ─── MOCK STORIES ──────────────────────────────────────────────────────────
// Still uses stub data — will be migrated when the stories collection is added.
export const MOCK_STORIES: Story[] = _MOCK_USER_STUBS.map((user: any, i: number) => ({
  id: `s${i + 1}`, userId: user.id, userAvatar: user.avatar, userName: user.name.split(' ')[0],
  userSport: user.sport as any, mediaUrl: user.coverImage || '',
  mediaType: 'image' as const, timestamp: new Date(Date.now() - i * 1800000).toISOString(), viewed: i > 2,
}));

// ─── MOCK EVENTS ───────────────────────────────────────────────────────────
export const MOCK_EVENTS: Event[] = [
  {
    id: 'e1', title: 'Pro Football 5v5 Championship', sport: 'football',
    description: 'Elite 5v5 indoor football tournament featuring top professionals from across Europe. AI-powered team balancing ensures competitive matchups.',
    date: '2025-06-15', venue: 'Berlin Indoor Arena', location: 'Berlin, Germany',
    format: 'tournament', skillLevel: 'professional',
    maxParticipants: 64, participants: ['u1', 'cu1', 'u3'],
    teams: [], organizerId: 'u1', status: 'upcoming', aiTeamAvailable: true, aiGenerated: false,
    prizePool: '€25,000', entryFee: '€150',
    rules: ['5v5 format', '10-minute halves', 'No offside', 'Unlimited substitutions'],
    tags: ['football', 'professional', 'indoor', 'europe'],
    bannerImage: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80',
    createdAt: '2025-04-01',
  },
  {
    id: 'e2', title: 'Asia Pacific Basketball Open', sport: 'basketball',
    description: 'Premier 3x3 basketball tournament in Tokyo. Join as a team or let AI match you with compatible teammates.',
    date: '2025-06-28', venue: 'Yoyogi National Gymnasium', location: 'Tokyo, Japan',
    format: 'tournament', skillLevel: 'semi-pro',
    maxParticipants: 48, participants: ['u3', 'u5'],
    teams: [], organizerId: 'u5', status: 'upcoming', aiTeamAvailable: true, aiGenerated: false,
    prizePool: '¥500,000', entryFee: '¥5,000',
    rules: ['3x3 format', '10-minute games', 'Win by 2 or first to 21'],
    tags: ['basketball', '3x3', 'asia', 'open'],
    bannerImage: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&q=80',
    createdAt: '2025-04-10',
  },
  {
    id: 'e3', title: 'Grand Prix Tennis Invitational', sport: 'tennis',
    description: 'Exclusive clay-court exhibition featuring top-50 ranked players. Singles and doubles formats available.',
    date: '2025-07-05', venue: 'Monte Carlo Country Club', location: 'Monaco',
    format: 'tournament', skillLevel: 'elite',
    maxParticipants: 32, participants: ['u2'],
    teams: [], organizerId: 'u2', status: 'upcoming', aiTeamAvailable: false, aiGenerated: false,
    prizePool: '€50,000', entryFee: 'Invitation Only',
    rules: ['Best of 3 sets', 'Clay surface', 'Hawk-Eye available'],
    tags: ['tennis', 'clay', 'elite', 'europe'],
    bannerImage: 'https://images.unsplash.com/photo-1547941126-3d5322b218b0?w=800&q=80',
    createdAt: '2025-04-15',
  },
  {
    id: 'e4', title: 'MMA Prospect Showcase', sport: 'mma',
    description: 'Platform for undefeated prospects to compete in front of global promoters. Sanctioned bouts, full medical staff.',
    date: '2025-07-20', venue: 'Saitama Super Arena', location: 'Saitama, Japan',
    format: 'tournament', skillLevel: 'professional',
    maxParticipants: 16, participants: ['u5'],
    teams: [], organizerId: 'u5', status: 'upcoming', aiTeamAvailable: false, aiGenerated: false,
    prizePool: '$100,000', entryFee: 'Invite Only',
    rules: ['MMA unified rules', '5x5 minute rounds', 'Weight classes: 145lb, 155lb, 170lb'],
    tags: ['mma', 'prospect', 'sanctioned'],
    bannerImage: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80',
    createdAt: '2025-04-20',
  },
  {
    id: 'e5', title: 'Berlin Metro Futsal Cup', sport: 'football',
    description: 'Dynamic 5v5 indoor football tournament held in the heart of Berlin. Featuring fast-paced games, street rules, and direct elimination rounds. Join solo or with a team.',
    date: '2025-06-25', venue: 'Berlin Sports Hub', location: 'Berlin, Germany',
    format: 'tournament', skillLevel: 'semi-pro',
    maxParticipants: 32, participants: ['cu1', 'u1', 'u2'],
    teams: [], organizerId: 'cu1', status: 'upcoming', aiTeamAvailable: true, aiGenerated: false,
    prizePool: '€5,000', entryFee: '€20',
    rules: ['5v5 format', '8-minute halves', 'Kick-ins instead of throw-ins', 'Sudden death penalty shootouts'],
    tags: ['football', 'futsal', 'indoor', 'berlin'],
    bannerImage: 'https://static.vecteezy.com/system/resources/previews/015/842/910/non_2x/football-tournament-sport-event-background-design-template-simple-and-elegant-design-vector.jpg',
    bannerAlignment: 'center',
    createdAt: '2025-05-01',
  },
  {
    id: 'e6', title: 'Elite Streetball Showdown', sport: 'basketball',
    description: 'Berlin\'s biggest 3x3 basketball competition. Play on the legendary Kreuzberg outdoor court. Heavy beats, food trucks, and high stakes.',
    date: '2025-07-10', venue: 'Kreuzberg Courts', location: 'Berlin, Germany',
    format: 'solo', skillLevel: 'professional',
    maxParticipants: 16, participants: ['cu1', 'u3', 'u4'],
    teams: [], organizerId: 'cu1', status: 'upcoming', aiTeamAvailable: true, aiGenerated: false,
    prizePool: '€3,500', entryFee: 'Free',
    rules: ['3x3 street rules', '12-second shot clock', 'First to 21 wins', 'All participants must wear official SportiX jerseys'],
    tags: ['basketball', 'streetball', '3x3', 'berlin'],
    bannerImage: 'https://th.bing.com/th/id/R.2d63531a411e6e80d02b85dd676f8e7d?rik=CGfgkIE6r5kAnA&riu=http%3a%2f%2fwww.visitveniceca.com%2fwp-content%2fuploads%2f2017%2f05%2f3e650ad1-4823-4bd0-a737-61d152acbe2d-1-1024x683.jpg&ehk=8v9xWIrrQRlCWGQhvGsz79Obd8hTbnzO52of2E6M%2bqM%3d&risl=&pid=ImgRaw&r=0',
    bannerAlignment: 'top',
    createdAt: '2025-05-05',
  },
  {
    id: 'e7', title: 'Vanguard Clay Court Tennis Open', sport: 'tennis',
    description: 'An open amateur clay court tournament at Rot-Weiss Tennis Club. Standard brackets, double elimination, open to all tennis enthusiasts.',
    date: '2025-07-18', venue: 'Rot-Weiss Tennis Club', location: 'Berlin, Germany',
    format: 'league', skillLevel: 'amateur',
    maxParticipants: 24, participants: ['cu1', 'u2'],
    teams: [], organizerId: 'cu1', status: 'upcoming', aiTeamAvailable: false, aiGenerated: false,
    prizePool: 'Gear & Trophies', entryFee: '€15',
    rules: ['Best of 3 sets with super tie-break', 'Standard ITF rules apply', 'Players must bring their own rackets'],
    tags: ['tennis', 'clay', 'amateur', 'singles'],
    bannerImage: 'https://images.unsplash.com/photo-1560079007-f530de68e8bb?w=800&q=80',
    bannerAlignment: 'bottom',
    createdAt: '2025-05-10',
  },
  {
    id: 'e8', title: 'MMA Spree Ring Fight Night', sport: 'mma',
    description: 'An exclusive amateur showcase event featuring local talent from Berlin and surrounding areas. Full medical checks, amateur regulations, and professional refs.',
    date: '2025-08-05', venue: 'Spree Martial Arts Center', location: 'Berlin, Germany',
    format: 'tournament', skillLevel: 'elite',
    maxParticipants: 8, participants: ['cu1', 'u5'],
    teams: [], organizerId: 'cu1', status: 'upcoming', aiTeamAvailable: false, aiGenerated: false,
    prizePool: '€10,000', entryFee: 'Invite Only',
    rules: ['IMMAF rules apply', '3 rounds of 3 minutes', 'Shin guards and 7oz gloves required'],
    tags: ['mma', 'amateur', 'fightnight', 'showcase'],
    bannerImage: 'https://images.unsplash.com/photo-1595078475328-1ab05d0a6a0e?w=800&q=80',
    bannerAlignment: 'center',
    createdAt: '2025-05-12',
  },
  {
    id: 'e9', title: 'Chennai Futsal Derby 5v5', sport: 'football',
    description: 'Fast-paced futsal competition in Chennai. Bring your crew or let AI AutoSquad set up your team. High energy and cash prizes.',
    date: '2025-06-20', venue: 'Jawaharlal Nehru Stadium', location: 'Chennai, Tamil Nadu, India',
    format: 'tournament', skillLevel: 'semi-pro',
    maxParticipants: 40, participants: ['u6', 'cu1', 'u7'],
    teams: [], organizerId: 'cu1', status: 'upcoming', aiTeamAvailable: true, aiGenerated: false,
    prizePool: '₹50,000', entryFee: '₹500',
    rules: ['5v5 format', '15-minute halves', 'No offside', 'Rolling subs'],
    tags: ['football', 'futsal', 'chennai', 'derby'],
    bannerImage: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&q=80',
    createdAt: '2025-05-15',
  },
  {
    id: 'e10', title: 'Coimbatore Hoopfest 3x3', sport: 'basketball',
    description: 'Coimbatore\'s premiere 3x3 basketball battle. Showcase your skills, vertical jumps, and claim the hoop crown.',
    date: '2025-07-02', venue: 'Kovai Sports Arena', location: 'Coimbatore, Tamil Nadu, India',
    format: 'tournament', skillLevel: 'elite',
    maxParticipants: 32, participants: ['u9', 'u8'],
    teams: [], organizerId: 'u9', status: 'upcoming', aiTeamAvailable: true, aiGenerated: false,
    prizePool: '₹30,000', entryFee: '₹300',
    rules: ['3x3 half court', '12-minute match', 'FIBA 3x3 rules apply'],
    tags: ['basketball', '3x3', 'coimbatore', 'hoopfest'],
    bannerImage: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&q=80',
    createdAt: '2025-05-18',
  },
  {
    id: 'e11', title: 'Marina Beach Volleyball Open', sport: 'volleyball',
    description: 'Annual beach volleyball tournament on the golden sands of Marina Beach. Spectacular views, high competition, open to all.',
    date: '2025-07-08', venue: 'Marina Beach Court', location: 'Chennai, Tamil Nadu, India',
    format: 'tournament', skillLevel: 'amateur',
    maxParticipants: 48, participants: ['u7', 'u6', 'u10'],
    teams: [], organizerId: 'u7', status: 'upcoming', aiTeamAvailable: true, aiGenerated: false,
    prizePool: '₹20,000', entryFee: '₹200',
    rules: ['2v2 format', 'Best of 3 sets', 'Standard FIVB beach rules'],
    tags: ['volleyball', 'beach', 'chennai', 'marina'],
    bannerImage: 'https://images.unsplash.com/photo-1519766304817-4f37bda74a27?w=800&q=80',
    createdAt: '2025-05-20',
  },
  {
    id: 'e12', title: 'Madurai Athletics Sprint Meet', sport: 'athletics',
    description: 'Find out who is the fastest athlete in Madurai! Track events from 100m to 800m. Powered by SportiX performance metrics.',
    date: '2025-07-15', venue: 'Race Course Stadium', location: 'Madurai, Tamil Nadu, India',
    format: 'solo', skillLevel: 'professional',
    maxParticipants: 100, participants: ['u8', 'cu1'],
    teams: [], organizerId: 'u8', status: 'upcoming', aiTeamAvailable: false, aiGenerated: false,
    prizePool: '₹40,000', entryFee: '₹100',
    rules: ['IAAF rules apply', 'Electronic timing', 'Spikes allowed'],
    tags: ['athletics', 'sprint', 'madurai', 'running'],
    bannerImage: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800&q=80',
    createdAt: '2025-05-22',
  },
  {
    id: 'e13', title: 'Trichy Cricket Super Bash', sport: 'cricket',
    description: 'Action-packed T10 cricket league in Trichy. Quick matches, powerplays, and big hitting guaranteed.',
    date: '2025-07-22', venue: 'Trichy Club Ground', location: 'Trichy, Tamil Nadu, India',
    format: 'league', skillLevel: 'semi-pro',
    maxParticipants: 80, participants: ['u7', 'u10'],
    teams: [], organizerId: 'u7', status: 'upcoming', aiTeamAvailable: true, aiGenerated: false,
    prizePool: '₹60,000', entryFee: '₹1000 per team',
    rules: ['T10 format', 'Max 2 overs per bowler', '3-over powerplay'],
    tags: ['cricket', 't10', 'trichy', 'bash'],
    bannerImage: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&q=80',
    createdAt: '2025-05-25',
  },
  {
    id: 'e14', title: 'Salem Tennis Cup', sport: 'tennis',
    description: 'Championship singles tennis tournament in Salem. Double-elimination format ensuring everyone gets ample match time.',
    date: '2025-07-28', venue: 'Salem Sports Association', location: 'Salem, Tamil Nadu, India',
    format: 'tournament', skillLevel: 'amateur',
    maxParticipants: 24, participants: ['u10', 'u2'],
    teams: [], organizerId: 'u10', status: 'upcoming', aiTeamAvailable: false, aiGenerated: false,
    prizePool: 'Trophies & Vouchers', entryFee: '₹300',
    rules: ['Best of 3 short sets', 'Standard tie-break at 4-4', 'Deuce sudden death'],
    tags: ['tennis', 'salem', 'championship'],
    bannerImage: 'https://images.unsplash.com/photo-1560079007-f530de68e8bb?w=800&q=80',
    createdAt: '2025-05-28',
  },
  {
    id: 'e15', title: 'Vellore Cyclothon', sport: 'cycling',
    description: 'Experience the scenic roads of Vellore in this 50KM cycle marathon. Open category for road, hybrid, and mountain bikes.',
    date: '2025-08-02', venue: 'Vellore Fort Start Point', location: 'Vellore, Tamil Nadu, India',
    format: 'solo', skillLevel: 'amateur',
    maxParticipants: 200, participants: ['u8', 'cu1'],
    teams: [], organizerId: 'u8', status: 'upcoming', aiTeamAvailable: false, aiGenerated: false,
    prizePool: '₹25,000', entryFee: '₹150',
    rules: ['Helmets mandatory', 'No drafting allowed for solo categories', 'GPS tracking required'],
    tags: ['cycling', 'marathon', 'vellore', 'scenic'],
    bannerImage: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80',
    createdAt: '2025-06-01',
  },
  {
    id: 'e16', title: 'Erode Athletics Championship', sport: 'athletics',
    description: 'Erode district athletics meet covering track and field events. Come compete or support the next generation of stars.',
    date: '2025-08-10', venue: 'Erode District Stadium', location: 'Erode, Tamil Nadu, India',
    format: 'solo', skillLevel: 'semi-pro',
    maxParticipants: 150, participants: ['u8', 'u6'],
    teams: [], organizerId: 'u8', status: 'upcoming', aiTeamAvailable: false, aiGenerated: false,
    prizePool: 'Medals & Trophies', entryFee: '₹50',
    rules: ['District guidelines apply', 'Age verification required', 'Max 3 events per athlete'],
    tags: ['athletics', 'erode', 'championship'],
    bannerImage: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800&q=80',
    createdAt: '2025-06-03',
  },
  {
    id: 'e17', title: 'Chennai Boxing Fight Night', sport: 'boxing',
    description: 'Live boxing event under the lights in Chennai. Standard amateur regulations apply. Matchups generated by SportiX AI matchmaking.',
    date: '2025-08-18', venue: 'Chennai Boxing Club', location: 'Chennai, Tamil Nadu, India',
    format: 'tournament', skillLevel: 'professional',
    maxParticipants: 16, participants: ['u7', 'u9'],
    teams: [], organizerId: 'u7', status: 'upcoming', aiTeamAvailable: false, aiGenerated: false,
    prizePool: '₹75,000', entryFee: '₹500',
    rules: ['Amateur boxing rules', '3 rounds of 3 minutes', 'Headgear optional for senior elite'],
    tags: ['boxing', 'fightnight', 'chennai', 'clash'],
    bannerImage: 'https://images.unsplash.com/photo-1595078475328-1ab05d0a6a0e?w=800&q=80',
    createdAt: '2025-06-05',
  },
  {
    id: 'e18', title: 'Marina Beach Running Challenge', sport: 'athletics',
    description: 'A beautiful morning run along the longest beach in India. Choose between 5K, 10K, and 21K options.',
    date: '2025-08-25', venue: 'Marina Light House', location: 'Chennai, Tamil Nadu, India',
    format: 'solo', skillLevel: 'amateur',
    maxParticipants: 300, participants: ['cu1', 'u8', 'u6'],
    teams: [], organizerId: 'u8', status: 'upcoming', aiTeamAvailable: false, aiGenerated: false,
    prizePool: '₹35,000', entryFee: '₹200',
    rules: ['Time-chip tracking', 'Hydration stations every 2KM', 'Cutoff time 3.5 hours for 21K'],
    tags: ['running', 'marina', 'chennai', 'marathon'],
    bannerImage: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800&q=80',
    createdAt: '2025-06-08',
  },
  {
    id: 'e19', title: 'Coimbatore MMA Fight Night', sport: 'mma',
    description: 'Slamming cage action returns to Coimbatore. Watch elite amateur and pro fighters go toe-to-toe in the Octagon.',
    date: '2025-09-02', venue: 'Kovai Combat Club', location: 'Coimbatore, Tamil Nadu, India',
    format: 'tournament', skillLevel: 'elite',
    maxParticipants: 12, participants: ['u9', 'u7'],
    teams: [], organizerId: 'u9', status: 'upcoming', aiTeamAvailable: false, aiGenerated: false,
    prizePool: '₹80,000', entryFee: 'Invite Only',
    rules: ['Unified amateur MMA rules', '3 rounds of 3 minutes', 'Shin guards required'],
    tags: ['mma', 'fightnight', 'coimbatore'],
    bannerImage: 'https://images.unsplash.com/photo-1595078475328-1ab05d0a6a0e?w=800&q=80',
    createdAt: '2025-06-10',
  },
  {
    id: 'e20', title: 'Madurai Marathon', sport: 'athletics',
    description: 'Celebrate the spirit of Madurai! Run past historical landmarks in a full 42KM marathon, or join the 10K fun run.',
    date: '2025-09-10', venue: 'Madurai Temple Grounds', location: 'Madurai, Tamil Nadu, India',
    format: 'solo', skillLevel: 'amateur',
    maxParticipants: 500, participants: ['u8', 'cu1', 'u10'],
    teams: [], organizerId: 'u8', status: 'upcoming', aiTeamAvailable: false, aiGenerated: false,
    prizePool: '₹1,00,000', entryFee: '₹250',
    rules: ['Standard marathon regulations', 'Finisher medals for all within cutoff', 'Water & medical support provided'],
    tags: ['running', 'madurai', 'marathon', 'historic'],
    bannerImage: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&q=80',
    createdAt: '2025-06-12',
  },
  {
    id: 'e21', title: 'Tirunelveli Kabaddi Championship', sport: 'volleyball',
    description: 'Kabaddi tournament in Tirunelveli. Elite district players competing for the championship.',
    date: '2025-09-18', venue: 'Tirunelveli Sports Complex', location: 'Tirunelveli, Tamil Nadu, India',
    format: 'tournament', skillLevel: 'professional',
    maxParticipants: 32, participants: ['u6', 'u7'],
    teams: [], organizerId: 'cu1', status: 'upcoming', aiTeamAvailable: false, aiGenerated: false,
    prizePool: '₹40,000', entryFee: '₹200',
    rules: ['Pro Kabaddi rules apply', 'Standard mats', 'Weight limit strict'],
    tags: ['kabaddi', 'tirunelveli', 'tournament'],
    bannerImage: 'https://images.unsplash.com/photo-1519766304817-4f37bda74a27?w=800&q=80',
    createdAt: '2025-06-15',
  },
  {
    id: 'e22', title: 'Kanyakumari Sunset Coastal Run', sport: 'athletics',
    description: 'A beautiful coastal run at the tip of India during sunset. 5K, 10K, and 15K categories.',
    date: '2025-09-25', venue: 'Sunset View Point', location: 'Kanyakumari, Tamil Nadu, India',
    format: 'solo', skillLevel: 'amateur',
    maxParticipants: 200, participants: ['u8', 'u6'],
    teams: [], organizerId: 'u8', status: 'upcoming', aiTeamAvailable: false, aiGenerated: false,
    prizePool: '₹20,000', entryFee: '₹100',
    rules: ['Scenic running track', 'Hydration points provided', 'Cutoff time 2.5 hours'],
    tags: ['running', 'kanyakumari', 'coastal'],
    bannerImage: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800&q=80',
    createdAt: '2025-06-18',
  },
  {
    id: 'e23', title: 'Tuticorin Port City Football Clash', sport: 'football',
    description: 'Elite 7v7 football clash under floodlights. High stakes, local rivalry.',
    date: '2025-10-02', venue: 'Port Trust Ground', location: 'Tuticorin, Tamil Nadu, India',
    format: 'tournament', skillLevel: 'semi-pro',
    maxParticipants: 24, participants: ['u6', 'u10'],
    teams: [], organizerId: 'cu1', status: 'upcoming', aiTeamAvailable: true, aiGenerated: false,
    prizePool: '₹35,000', entryFee: '₹400',
    rules: ['7v7 layout', '12-minute halves', 'Rolling substitutions', 'Offside rule simplified'],
    tags: ['football', 'tuticorin', 'clash'],
    bannerImage: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&q=80',
    createdAt: '2025-06-20',
  },
  {
    id: 'e24', title: 'Thanjavur Palace Badminton Open', sport: 'tennis',
    description: 'Open badminton / singles tennis tournament inside Thanjavur. Standard brackets, double elimination.',
    date: '2025-10-10', venue: 'Palace Indoor Court', location: 'Thanjavur, Tamil Nadu, India',
    format: 'tournament', skillLevel: 'amateur',
    maxParticipants: 32, participants: ['u10', 'u2'],
    teams: [], organizerId: 'u10', status: 'upcoming', aiTeamAvailable: false, aiGenerated: false,
    prizePool: '₹20,000', entryFee: '₹150',
    rules: ['ITF single rules apply', 'Synthetic courts', 'Knockout format'],
    tags: ['tennis', 'thanjavur', 'badminton'],
    bannerImage: 'https://images.unsplash.com/photo-1560079007-f530de68e8bb?w=800&q=80',
    createdAt: '2025-06-22',
  },
  {
    id: 'e25', title: 'Dindigul Rock Fort Track Meet', sport: 'athletics',
    description: 'Track meet held under the historic Dindigul Rock Fort. Metric tracking enabled.',
    date: '2025-10-18', venue: 'Fort Ground Arena', location: 'Dindigul, Tamil Nadu, India',
    format: 'solo', skillLevel: 'semi-pro',
    maxParticipants: 120, participants: ['u8', 'u7'],
    teams: [], organizerId: 'u8', status: 'upcoming', aiTeamAvailable: false, aiGenerated: false,
    prizePool: '₹30,000', entryFee: '₹100',
    rules: ['IAAF rules apply', 'Electronic timers', 'Running spikes allowed'],
    tags: ['athletics', 'dindigul', 'running'],
    bannerImage: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800&q=80',
    createdAt: '2025-06-25',
  },
  {
    id: 'e26', title: 'Vellore Fort Futsal League', sport: 'football',
    description: 'Fast futsal league in Vellore. Build your squad or let AI matchmaking do the work.',
    date: '2025-10-25', venue: 'Fort View Turf', location: 'Vellore, Tamil Nadu, India',
    format: 'league', skillLevel: 'semi-pro',
    maxParticipants: 16, participants: ['u6', 'u7'],
    teams: [], organizerId: 'cu1', status: 'upcoming', aiTeamAvailable: true, aiGenerated: false,
    prizePool: '₹25,000', entryFee: '₹300',
    rules: ['5v5 format', '10-minute halves', 'Rolling substitutions', 'Kick-ins allowed'],
    tags: ['football', 'futsal', 'vellore'],
    bannerImage: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&q=80',
    createdAt: '2025-06-28',
  },
  {
    id: 'e27', title: 'Hosur Industrial Hoopfest 3x3', sport: 'basketball',
    description: 'Hosur 3x3 street basketball battle. Build team or join as solo agent.',
    date: '2025-11-02', venue: 'Hosur Indoor Gym', location: 'Hosur, Tamil Nadu, India',
    format: 'tournament', skillLevel: 'semi-pro',
    maxParticipants: 24, participants: ['u9', 'u8'],
    teams: [], organizerId: 'u9', status: 'upcoming', aiTeamAvailable: true, aiGenerated: false,
    prizePool: '₹35,000', entryFee: '₹200',
    rules: ['3x3 half court', 'FIBA rules', 'Rolling subs'],
    tags: ['basketball', 'hosur', '3x3'],
    bannerImage: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&q=80',
    createdAt: '2025-07-01',
  },
  {
    id: 'e28', title: 'Salem Cage Fight Night MMA', sport: 'mma',
    description: 'High-octane MMA battles returns to Salem. Sanctioned bouts under the lights.',
    date: '2025-11-10', venue: 'Salem Arena Center', location: 'Salem, Tamil Nadu, India',
    format: 'tournament', skillLevel: 'elite',
    maxParticipants: 16, participants: ['u9', 'u7'],
    teams: [], organizerId: 'u9', status: 'upcoming', aiTeamAvailable: false, aiGenerated: false,
    prizePool: '₹60,000', entryFee: 'Invite Only',
    rules: ['IMMAF rules', '3 rounds of 3 mins', 'Full gear required'],
    tags: ['mma', 'fightnight', 'salem'],
    bannerImage: 'https://images.unsplash.com/photo-1595078475328-1ab05d0a6a0e?w=800&q=80',
    createdAt: '2025-07-03',
  },
];

// ─── MOCK CONVERSATIONS ────────────────────────────────────────────────────
export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'c1', participants: ['cu1', 'u1'],
    participantDetails: [{ id: 'u1', name: 'Marcus Thielemann', avatar: ph('u1'), isOnline: true }],
    lastMessage: { id: 'm1', conversationId: 'c1', senderId: 'u1', content: 'Bro that sprint data is insane, what tracker are you using?', timestamp: new Date(Date.now() - 1800000).toISOString(), read: false },
    unreadCount: 3, isEventChat: false, createdAt: '2025-01-01', updatedAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'c2', participants: ['cu1', 'u2'],
    participantDetails: [{ id: 'u2', name: 'Priya Krishnamurthy', avatar: ph('u2'), isOnline: false }],
    lastMessage: { id: 'm2', conversationId: 'c2', senderId: 'cu1', content: 'Good luck at Roland Garros! You\'ve got this 🎾', timestamp: new Date(Date.now() - 7200000).toISOString(), read: true },
    unreadCount: 0, isEventChat: false, createdAt: '2025-01-15', updatedAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'c3', participants: ['cu1', 'u3', 'u5'],
    participantDetails: [
      { id: 'u3', name: 'DeShawn Williams', avatar: ph('u3'), isOnline: true },
      { id: 'u5', name: 'Yuki Tanaka', avatar: ph('u5'), isOnline: true },
    ],
    lastMessage: { id: 'm3', conversationId: 'c3', senderId: 'u3', content: 'Team is confirmed! See you all at the arena 🏀', timestamp: new Date(Date.now() - 3600000).toISOString(), read: false },
    unreadCount: 7, isEventChat: true, eventId: 'e2', eventName: 'Asia Pacific Basketball Open',
    createdAt: '2025-03-01', updatedAt: new Date(Date.now() - 3600000).toISOString(),
  },
];

export const MOCK_MESSAGES: Record<string, Message[]> = {
  c1: [
    { id: 'm1a', conversationId: 'c1', senderId: 'u1', content: 'Hey man, saw your 400m splits last week. Absolute unit.', timestamp: new Date(Date.now() - 3600000 * 5).toISOString(), read: true },
    { id: 'm1b', conversationId: 'c1', senderId: 'cu1', content: 'Thanks Marcus! Been grinding the lactate threshold work. You should try the Polar Vantage V3 for HRV tracking.', timestamp: new Date(Date.now() - 3600000 * 4).toISOString(), read: true },
    { id: 'm1c', conversationId: 'c1', senderId: 'u1', content: 'Bro that sprint data is insane, what tracker are you using?', timestamp: new Date(Date.now() - 1800000).toISOString(), read: false },
  ],
  c2: [
    { id: 'm2a', conversationId: 'c2', senderId: 'cu1', content: 'Priya! Watched your training highlights. Your backhand cross-court is lethal now.', timestamp: new Date(Date.now() - 86400000).toISOString(), read: true },
    { id: 'm2b', conversationId: 'c2', senderId: 'u2', content: '3 years of work on that shot. Finally feels automatic. Thanks for noticing!', timestamp: new Date(Date.now() - 82800000).toISOString(), read: true },
    { id: 'm2c', conversationId: 'c2', senderId: 'cu1', content: 'Good luck at Roland Garros! You\'ve got this 🎾', timestamp: new Date(Date.now() - 7200000).toISOString(), read: true },
  ],
  c3: [
    { id: 'm3a', conversationId: 'c3', senderId: 'u5', content: 'SportiX matched us for the Tokyo tournament. Ready to ball out?', timestamp: new Date(Date.now() - 7200000).toISOString(), read: true },
    { id: 'm3b', conversationId: 'c3', senderId: 'cu1', content: 'Let\'s go! The AI picked a solid lineup tbh.', timestamp: new Date(Date.now() - 5400000).toISOString(), read: true },
    { id: 'm3c', conversationId: 'c3', senderId: 'u3', content: 'Team is confirmed! See you all at the arena 🏀', timestamp: new Date(Date.now() - 3600000).toISOString(), read: false },
  ],
};

// ─── MOCK NOTIFICATIONS ────────────────────────────────────────────────────
export const MOCK_NOTIFICATIONS: Notification[] = [
  { id: 'n1', userId: 'cu1', type: 'event_invite', title: 'Event Invitation', message: 'Marcus Thielemann invited you to join Pro Football 5v5 Championship', read: false, timestamp: new Date(Date.now() - 1800000).toISOString(), relatedId: 'e1', actorAvatar: ph('u1'), actorName: 'Marcus Thielemann' },
  { id: 'n2', userId: 'cu1', type: 'ai_match', title: 'AI Team Match', message: 'SportiX AI found you 3 compatible teammates for Asia Pacific Basketball Open', read: false, timestamp: new Date(Date.now() - 3600000).toISOString(), relatedId: 'e2', actorName: 'SportiX AI' },
  { id: 'n3', userId: 'cu1', type: 'like', title: 'New Like', message: 'Isabela Moraes liked your training post', read: false, timestamp: new Date(Date.now() - 7200000).toISOString(), relatedId: 'p1', actorAvatar: ph('u4'), actorName: 'Isabela Moraes' },
  { id: 'n4', userId: 'cu1', type: 'connection_request', title: 'Connection Request', message: 'Yuki Tanaka wants to connect with you', read: true, timestamp: new Date(Date.now() - 86400000).toISOString(), actorAvatar: ph('u5'), actorName: 'Yuki Tanaka' },
  { id: 'n5', userId: 'cu1', type: 'match_reminder', title: 'Match Reminder', message: 'Pro Football 5v5 Championship starts in 48 hours', read: true, timestamp: new Date(Date.now() - 86400000 * 2).toISOString(), relatedId: 'e1' },
  { id: 'n6', userId: 'cu1', type: 'achievement', title: 'New Achievement', message: 'You unlocked "Early Adopter" — joined SportiX in the first wave', read: true, timestamp: new Date(Date.now() - 86400000 * 3).toISOString() },
];
