from app.routers import (
    auth,
    users,
    posts,
    stories,
    reels,
    events,
    squads,
    matches,
    pulse,
    missions,
    coins,
    badges,
    notifications,
    leaderboard,
    autosquad,
    search,
    upload,
    settings,
    admin,
    sports,
)

__all__ = [
    "auth", "users", "posts", "stories", "reels",
    "events", "squads", "matches", "pulse",
    "missions", "coins", "badges", "notifications",
    "leaderboard", "autosquad", "search",
    "upload", "settings", "admin", "sports",
]
